version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  # snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.2
    steps:
      - checkout
      - run: mvn clean spring-boot:run

  test:
    docker:
      - image: cimg/openjdk:20.0.2
      - image: cimg/postgres:12.17
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple-library
    steps:
      - checkout
      - run: 
          name: Wait for db to run
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mvn test

  # scan:
  #   docker:
  #     - image: cimg/openjdk:20.0.2
  #   environment:
  #     IMAGE_NAME: revvrel/simple-library
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - docker/check
  #     - run: docker build -t $IMAGE_NAME
  #     - snyk/scan:
  #         docker-image-name: $IMAGE_NAME

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: revvrel/simple-library
          tag: v1.0.0
      - docker/push:
          image: revvrel/simple-library
          tag: v1.0.0

  deploy:
    docker:
      - image: cimg/openjdk:20.0.2
      - image: cimg/postgres:12.17
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple-library
          DATABASE_URL: postgresql://localhost:5432/simple-library
        ports: 
          - 5432:5432
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run: 
          name: Wait for db to run
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Heroku Container Push
          command: |
              heroku container:login
              heroku container:push web -a module4-simple-library
              heroku container:release web -a module4-simple-library

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      # - scan:
      #     requires:
      #       - test
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish