version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.2
    steps:
      - checkout
      - run: mvn clean spring-boot:run

  test:
    docker:
      - image: cimg/openjdk:20.0.2
    steps:
      - checkout
      - run: mvn clean spring-boot:run

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: revvrel/simple-library
          tag: v1.0.0
      - docker/push:
          image: revvrel/simple-library
          tag: v1.0.0

  deploy:
    docker:
      - image: cimg/openjdk:20.0.2
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run:
          name: Heroku Container Push
          command: |
              heroku container:login
              heroku container:push web -a module4-simple-library
              heroku container:release web -a module4-simple-library


workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      -deploy:
          requires:
            - publish